from django.urls import path

from . import views

urlpatterns = [path("index.html", views.index, name="index"),
	       path('FarmerLogin.html', views.FarmerLogin, name="FarmerLogin"), 
	       path('FarmerLoginAction', views.FarmerLoginAction, name="FarmerLoginAction"),
           path('FarmerDashboard/', views.FarmerDashboard, name='FarmerDashboard'),
	       path('ExpertLogin.html', views.ExpertLogin, name="ExpertLogin"), 
	       path('ExpertLoginAction', views.ExpertLoginAction, name="ExpertLoginAction"),
           path('ExpertDashboard/', views.ExpertDashboard, name='ExpertDashboard'),
	       path('AdminLogin.html', views.AdminLogin, name="AdminLogin"), 
	       path('AdminLoginAction', views.AdminLoginAction, name="AdminLoginAction"),
           path('AdminDashboard/', views.AdminDashboard, name='AdminDashboard'),
           path("ViewFarmers", views.ViewFarmers, name="ViewFarmers"),
           path("ViewApprovedExperts", views.ViewApprovedExperts, name="ViewApprovedExperts"),
	       path('ExpertRegister.html', views.ExpertRegister, name="ExpertRegister"),
	       path('ExpertRegisterAction', views.ExpertRegisterAction, name="ExpertRegisterAction"),
	       path('FarmerRegister.html', views.FarmerRegister, name="FarmerRegister"),
	       path('FarmerRegisterAction', views.FarmerRegisterAction, name="FarmerRegisterAction"),
	       path("Contactus.html", views.Contactus, name="Contactus"),
	       path("Aboutus.html", views.Aboutus, name="Aboutus"),
           path("help.html", views.help, name="help"),
           path("login.html", views.login, name="login"),
           path("register.html", views.register, name="register"),
	       path('ApproveAccount', views.ApproveAccount, name="ApproveAccount"),
	       path('ApproveAccountAction', views.ApproveAccountAction, name="ApproveAccountAction"),
	       path('UpdatePrices.html', views.UpdatePrices, name="UpdatePrices"),
	       path('UpdatePricesAction', views.UpdatePricesAction, name="UpdatePricesAction"),
	       path('ViewQueryResult', views.ViewQueryResult, name="ViewQueryResult"),
	       path('PostPolicies.html', views.PostPolicies, name="PostPolicies"),
	       path('PostPoliciesAction', views.PostPoliciesAction, name="PostPoliciesAction"),
	       path('UploadGuide.html', views.UploadGuide, name="UploadGuide"),
	       path('UploadGuideAction', views.UploadGuideAction, name="UploadGuideAction"),
	       path('ResponseQuery.html', views.ResponseQuery, name="ResponseQuery"),
	       path('ResponseQueryAction', views.ResponseQueryAction, name="ResponseQueryAction"),
	       path('QueryResponse', views.QueryResponse, name="QueryResponse"),
	       path('VerifySuggestion.html', views.VerifySuggestion, name="VerifySuggestion"),
	       path('VerifySuggestionAction', views.VerifySuggestionAction, name="VerifySuggestionAction"),
           path("SaveVerification", views.SaveVerification, name="SaveVerification"),
           path('ExpertProfile/', views.ExpertProfile, name="ExpertProfile"),
           path('FarmerProfile/', views.FarmerProfile, name='FarmerProfile'),
           path('ChangeExpertPassword', views.ChangeExpertPassword, name="ChangeExpertPassword"),
	       path('Download', views.Download, name="Download"),
	       path('AccessSchemes', views.AccessSchemes, name="AccessSchemes"),
	       path('AISuggestion', views.AISuggestion, name="AISuggestion"),
	       path('SearchNetwork', views.SearchNetwork, name="SearchNetwork"),
	       path('QueryResponses', views.QueryResponses, name="QueryResponses"),
	       path('PostQuery.html', views.PostQuery, name="PostQuery"),
	       path('PostQueryAction', views.PostQueryAction, name="PostQueryAction"),
	       path('ViewGuide.html', views.ViewGuide, name="ViewGuide"),
	    #    path('ViewGuideAction', views.ViewGuideAction, name="ViewGuideAction"),
	       path('Chatbot', views.Chatbot, name="Chatbot"),
	       path('TextChatData', views.TextChatData, name="TextChatData"),
	       path('ViewCropRate', views.ViewCropRate, name="ViewCropRate"),
	       path('Back', views.Back, name="Back"),
	       path('Fertilizer', views.Fertilizer, name="Fertilizer"),
	    #    path('FertilizerAction', views.FertilizerAction, name="FertilizerAction"),
	       path('Yield', views.Yield, name="Yield"),	
	    #    path('YieldAction', views.YieldAction, name="YieldAction"),
	       path('Disease', views.Disease, name="Disease"),	
]